model_paths:
  yolov8n: models/pt/yolov8n.pt
  yolov8s: models/pt/yolov8s.pt
  yolov8m: models/pt/yolov8m.pt

gflops_map:
  YOLOv8n: 8.1
  YOLOv8s: 28.4
  YOLOv8m: 78.7

dataset:
  input_dir: ./images/
  annos_dir: ./annotations/
  output_dir: ./dataset/
  data_yaml: ./dataset/data.yaml

params: 
  confidence_threshold: 0.1
